### PR TITLE
added Fibonacci search for python

### PR DESCRIPTION
**Pull request by Dolamu-TheDataGuy**

### CODE REVIEW

**Comment by Ndohjapan** [comment]
You no even waste time, you don drop PR and with 2 minutes you have merged  😂😂

Don't forget to leave a star on the project

**Comment by Dolamu-TheDataGuy** [comment]
Lol, I'm sorry boss

But is it because I  am contributor that I am able to merge?

**Comment by Ndohjapan** [comment]
No I do not have a problem with that.

You can keep creating PR at atleast one PR for one issue or update.

I will simply review it and then merge.

I just learnt how to restrict merging requests to avoid having conflicts.

**Comment by Dolamu-TheDataGuy** [comment]
Alright

**Pull request merged**
